using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Dynamic_365_Role_Extractor.Utilities
{
    public class Utility
    {
        public static Dictionary<string, string> EntityGroups = new Dictionary<string, string>();
        public static Dictionary<string, string> MiscPermissionMap = new Dictionary<string, string>();

        static Utility()
        {
            EntityGroups.Add("Action Card", "Core Records");
            EntityGroups.Add("Action Card User Settings", "Core Records");
            EntityGroups.Add("Activity", "Core Records");
            EntityGroups.Add("Announcement", "Core Records");
            EntityGroups.Add("Application File", "Core Records");
            EntityGroups.Add("Category", "Core Records");
            EntityGroups.Add("Company", "Core Records");
            EntityGroups.Add("Connection", "Core Records");
            EntityGroups.Add("Connection Role", "Core Records");
            EntityGroups.Add("Customer Relationship", "Core Records");
            EntityGroups.Add("Data Import", "Core Records");
            EntityGroups.Add("Data Map", "Core Records");
            EntityGroups.Add("Data Performance Dashboard", "Core Records");
            EntityGroups.Add("Document Location", "Core Records");
            EntityGroups.Add("Document Suggestions", "Core Records");
            EntityGroups.Add("Duplicate Detection Rule", "Core Records");
            EntityGroups.Add("Email Signature", "Core Records");
            EntityGroups.Add("Email Template", "Core Records");
            EntityGroups.Add("Feedback", "Core Records");
            EntityGroups.Add("Follow", "Core Records");
            EntityGroups.Add("Import Source File", "Core Records");
            EntityGroups.Add("Interaction for Email", "Core Records");
            EntityGroups.Add("Language", "Core Records");
            EntityGroups.Add("Mail Merge Template", "Core Records");
            EntityGroups.Add("Mobile Offline Profile", "Core Records");
            EntityGroups.Add("Note", "Core Records");
            EntityGroups.Add("Opportunity", "Core Records");
            EntityGroups.Add("Opportunity Relationship", "Core Records");
            EntityGroups.Add("Person", "Core Records");
            EntityGroups.Add("Post", "Core Records");
            EntityGroups.Add("Prospect", "Core Records");
            EntityGroups.Add("Queue", "Core Records");
            EntityGroups.Add("Relationship Role", "Core Records");
            EntityGroups.Add("Report", "Core Records");
            EntityGroups.Add("Saved Organization Insights Configuration", "Core Records");
            EntityGroups.Add("Saved View", "Core Records");
            EntityGroups.Add("SharePoint Site", "Core Records");
            EntityGroups.Add("Social Profile", "Core Records");
            EntityGroups.Add("Subject", "Core Records");
            EntityGroups.Add("Sync Error", "Core Records");
            EntityGroups.Add("Trace", "Core Records");
            EntityGroups.Add("User Chart", "Core Records");
            EntityGroups.Add("User Dashboard", "Core Records");
            EntityGroups.Add("User Entity Instance Data", "Core Records");
            EntityGroups.Add("User Entity UI Settings", "Core Records");
            EntityGroups.Add("User Mapping", "Core Records");
            EntityGroups.Add("Web Wizard", "Core Records");
            EntityGroups.Add("Web Wizard Access Privilege", "Core Records");
            EntityGroups.Add("Wizard Page", "Core Records");

            EntityGroups.Add("Add Reporting Services Reports", "Core Records.Miscellaneous Privileges");
            EntityGroups.Add("Delete Audit Partitions", "Core Records.Miscellaneous Privileges");
            EntityGroups.Add("Manage Data Encryption key - Change", "Core Records.Miscellaneous Privileges");
            EntityGroups.Add("Manage User Synchronization Filters", "Core Records.Miscellaneous Privileges");
            EntityGroups.Add("Publish Email Templates", "Core Records.Miscellaneous Privileges");
            EntityGroups.Add("Publish Reports", "Core Records.Miscellaneous Privileges");
            EntityGroups.Add("View Audit History", "Core Records.Miscellaneous Privileges");
            EntityGroups.Add("View Audit Summary", "Core Records.Miscellaneous Privileges");
            EntityGroups.Add("Bulk Delete", "Core Records.Miscellaneous Privileges");
            EntityGroups.Add("Manage Data Encryption key - Activate", "Core Records.Miscellaneous Privileges");
            EntityGroups.Add("Manage Data Encryption key - Read", "Core Records.Miscellaneous Privileges");
            EntityGroups.Add("Publish Duplicate Detection Rules", "Core Records.Miscellaneous Privileges");
            EntityGroups.Add("Publish Mail Merge Templates to Organization", "Core Records.Miscellaneous Privileges");
            EntityGroups.Add("Run SharePoint Integration Wizard", "Core Records.Miscellaneous Privileges");
            EntityGroups.Add("View Audit Partitions", "Core Records.Miscellaneous Privileges");
            EntityGroups.Add("OneDrive for Business", "Core Records.Miscellaneous Privileges");
            EntityGroups.Add("Delete Audit Record Change History", "Core Records.Miscellaneous Privileges");


            EntityGroups.Add("Campaign", "Marketing");
            EntityGroups.Add("Marketing List", "Marketing");
            EntityGroups.Add("Configure Internet Marketing module", "Marketing.Miscellaneous Privileges");
            EntityGroups.Add("Use internet marketing module", "Marketing.Miscellaneous Privileges");
            EntityGroups.Add("Create Quick Campaign", "Marketing.Miscellaneous Privileges");


            EntityGroups.Add("Competitor", "Sales");
            EntityGroups.Add("Invoice", "Sales");
            EntityGroups.Add("Order", "Sales");
            EntityGroups.Add("Product", "Sales");
            EntityGroups.Add("Property", "Sales");
            EntityGroups.Add("Property Association", "Sales");
            EntityGroups.Add("Property Instance", "Sales");
            EntityGroups.Add("Property Option Set Item", "Sales");
            EntityGroups.Add("Quote", "Sales");
            EntityGroups.Add("Sales Literature", "Sales");
            EntityGroups.Add("Territory", "Sales");
            EntityGroups.Add("Override Invoice Pricing", "Sales.Miscellaneous Privileges");
            EntityGroups.Add("Override Order Pricing", "Sales.Miscellaneous Privileges");
            EntityGroups.Add("Override Quote Pricing", "Sales.Miscellaneous Privileges");
            EntityGroups.Add("Override Opportunity Pricing", "Sales.Miscellaneous Privileges");
            EntityGroups.Add("Override Quote Order Invoice Delete", "Sales.Miscellaneous Privileges");

            EntityGroups.Add("Article", "Service");
            EntityGroups.Add("Article Template", "Service");
            EntityGroups.Add("Bookable Resource", "Service");
            EntityGroups.Add("Bookable Resource Booking", "Service");
            EntityGroups.Add("Bookable Resource Booking Header", "Service");
            EntityGroups.Add("Bookable Resource Category", "Service");
            EntityGroups.Add("Bookable Resource Category Assn", "Service");
            EntityGroups.Add("Bookable Resource Characteristic", "Service");
            EntityGroups.Add("Bookable Resource Group", "Service");
            EntityGroups.Add("Booking Status", "Service");
            EntityGroups.Add("Case", "Service");
            EntityGroups.Add("Characteristic", "Service");
            EntityGroups.Add("Contract", "Service");
            EntityGroups.Add("Contract Template", "Service");
            EntityGroups.Add("Knowledge Article", "Service");
            EntityGroups.Add("KnowledgeArticle Views", "Service");
            EntityGroups.Add("Rating Model", "Service");
            EntityGroups.Add("Rating Value", "Service");
            EntityGroups.Add("Approve Knowledge Articles", "Service.Miscellaneous Privileges");
            EntityGroups.Add("Publish Knowledge Articles", "Service.Miscellaneous Privileges");
            EntityGroups.Add("Publish Articles", "Service.Miscellaneous Privileges");

            EntityGroups.Add("Business Unit", "Business Managment");
            EntityGroups.Add("Channel Property Group", "Business Managment");
            EntityGroups.Add("Currency", "Business Managment");
            EntityGroups.Add("Document Template", "Business Managment");
            EntityGroups.Add("Email Server Profile", "Business Managment");
            EntityGroups.Add("Field Security Profile", "Business Managment");
            EntityGroups.Add("Field Sharing", "Business Managment");
            EntityGroups.Add("Goal", "Business Managment");
            EntityGroups.Add("Goal Metric", "Business Managment");
            EntityGroups.Add("Mailbox", "Business Managment");
            EntityGroups.Add("Mailbox Auto Tracking Folder", "Business Managment");
            EntityGroups.Add("Organization", "Business Managment");
            EntityGroups.Add("Personal Document Template", "Business Managment");
            EntityGroups.Add("Position", "Business Managment");
            EntityGroups.Add("Principal Sync Attribute Map", "Business Managment");
            EntityGroups.Add("Rollup Query", "Business Managment");
            EntityGroups.Add("Security Role", "Business Managment");
            EntityGroups.Add("Sync Attribute Mapping Profile", "Business Managment");
            EntityGroups.Add("Team", "Business Managment");
            EntityGroups.Add("User", "Business Managment");
            EntityGroups.Add("User Settings", "Business Managment");

            EntityGroups.Add("Document Generation", "Business Management.Privacy Related Privileges");
            EntityGroups.Add("Dynamics 365 for phones express", "Business Management.Privacy Related Privileges");
            EntityGroups.Add("Go Offline in Outlook", "Business Management.Privacy Related Privileges");
            EntityGroups.Add("Print", "Business Management.Privacy Related Privileges");
            EntityGroups.Add("Use Dynamics 365 App for Outlook", "Business Management.Privacy Related Privileges");
            EntityGroups.Add("Dynamics 365 for mobile", "Business Management.Privacy Related Privileges");
            EntityGroups.Add("Export to Excel", "Business Management.Privacy Related Privileges");
            EntityGroups.Add("Mail Merge", "Business Management.Privacy Related Privileges");
            EntityGroups.Add("Sync to Outlook", "Business Management.Privacy Related Privileges");

            EntityGroups.Add("Act on Behalf of Another User", "Business Management.Miscellaneous Privileges");
            EntityGroups.Add("Assign manager for a user", "Business Management.Miscellaneous Privileges");
            EntityGroups.Add("Assign Territory to User", "Business Management.Miscellaneous Privileges");
            EntityGroups.Add("Change Hierarchy Security Settings", "Business Management.Miscellaneous Privileges");
            EntityGroups.Add("Enable or Disable Business Unit", "Business Management.Miscellaneous Privileges");
            EntityGroups.Add("Language Settings", "Business Management.Miscellaneous Privileges");
            EntityGroups.Add("Override Created on or Created by for Records during Data Import", "Business Management.Miscellaneous Privileges");
            EntityGroups.Add("Read License info", "Business Management.Miscellaneous Privileges");
            EntityGroups.Add("Reparent team", "Business Management.Miscellaneous Privileges");
            EntityGroups.Add("Send Email as Another User", "Business Management.Miscellaneous Privileges");
            EntityGroups.Add("Update Business Closures", "Business Management.Miscellaneous Privileges");
            EntityGroups.Add("Approve Email Addresses for Users or Queues", "Business Management.Miscellaneous Privileges");
            EntityGroups.Add("Assign position for a user", "Business Management.Miscellaneous Privileges");
            EntityGroups.Add("Bulk Edit", "Business Management.Miscellaneous Privileges");
            EntityGroups.Add("Dynamics 365 Address Book", "Business Management.Miscellaneous Privileges");
            EntityGroups.Add("Enable or Disable User", "Business Management.Miscellaneous Privileges");
            EntityGroups.Add("Merge", "Business Management.Miscellaneous Privileges");
            EntityGroups.Add("Perform in sync rollups on goals", "Business Management.Miscellaneous Privileges");
            EntityGroups.Add("Reparent Business unit", "Business Management.Miscellaneous Privileges");
            EntityGroups.Add("Reparent user", "Business Management.Miscellaneous Privileges");
            EntityGroups.Add("Send Invitation", "Business Management.Miscellaneous Privileges");
            EntityGroups.Add("Web Mail Merge", "Business Management.Miscellaneous Privileges");

            EntityGroups.Add("Calendar", "Service Managment");
            EntityGroups.Add("Entitlement", "Service Managment");
            EntityGroups.Add("Entitlement Template", "Service Managment");
            EntityGroups.Add("Facility/Equipment", "Service Managment");
            EntityGroups.Add("Knowledge Base Record", "Service Managment");
            EntityGroups.Add("Record Creation and Update Rule", "Service Managment");
            EntityGroups.Add("Routing Rule Set", "Service Managment");
            EntityGroups.Add("Service", "Service Managment");
            EntityGroups.Add("Site", "Service Managment");
            EntityGroups.Add("SLA", "Service Managment");
            EntityGroups.Add("SLA KPI Instance", "Service Managment");
            EntityGroups.Add("Browse Availability", "Service Management.Miscellaneous Privileges");
            EntityGroups.Add("Create own calendar", "Service Management.Miscellaneous Privileges");
            EntityGroups.Add("Read own calendar", "Service Management.Miscellaneous Privileges");
            EntityGroups.Add("Update Holiday Schedules", "Service Management.Miscellaneous Privileges");
            EntityGroups.Add("Control Decrement Terms", "Service Management.Miscellaneous Privileges");
            EntityGroups.Add("Delete own calendar", "Service Management.Miscellaneous Privileges");
            EntityGroups.Add("Search Availability", "Service Management.Miscellaneous Privileges");
            EntityGroups.Add("Write own calendar", "Service Management.Miscellaneous Privileges");

            EntityGroups.Add("App", "Customization");
            EntityGroups.Add("Attribute Map", "Customization");
            EntityGroups.Add("Custom Control", "Customization");
            EntityGroups.Add("Custom Control Default Config", "Customization");
            EntityGroups.Add("Custom Control Resource", "Customization");
            EntityGroups.Add("Customizations", "Customization");
            EntityGroups.Add("Entity", "Customization");
            EntityGroups.Add("Entity Key", "Customization");
            EntityGroups.Add("Entity Map", "Customization");
            EntityGroups.Add("Field", "Customization");
            EntityGroups.Add("Hierarchy Rule", "Customization");
            EntityGroups.Add("Import Job", "Customization");
            EntityGroups.Add("Option Set", "Customization");
            EntityGroups.Add("Plug-in Assembly", "Customization");
            EntityGroups.Add("Plug-in Trace Log", "Customization");
            EntityGroups.Add("Plug-in Type", "Customization");
            EntityGroups.Add("Process", "Customization");
            EntityGroups.Add("Process Configuration", "Customization");
            EntityGroups.Add("Process Session", "Customization");
            EntityGroups.Add("Publisher", "Customization");
            EntityGroups.Add("Relationship", "Customization");
            EntityGroups.Add("Sdk Message", "Customization");
            EntityGroups.Add("Sdk Message Processing Step", "Customization");
            EntityGroups.Add("Sdk Message Processing Step Image", "Customization");
            EntityGroups.Add("Sdk Message Processing Step Secure Configuration", "Customization");
            EntityGroups.Add("Service Endpoint", "Customization");
            EntityGroups.Add("Solution", "Customization");
            EntityGroups.Add("System Application Metadata", "Customization");
            EntityGroups.Add("System Chart", "Customization");
            EntityGroups.Add("System Form", "Customization");
            EntityGroups.Add("System Job", "Customization");
            EntityGroups.Add("Theme", "Customization");
            EntityGroups.Add("User Application Metadata", "Customization");
            EntityGroups.Add("View", "Customization");
            EntityGroups.Add("Web Resource", "Customization");
            EntityGroups.Add("Activate Business Process Flows", "Customization.Miscellaneous Privileges");
            EntityGroups.Add("Activate Real-time Processes", "Customization.Miscellaneous Privileges");
            EntityGroups.Add("Execute Workflow Job", "Customization.Miscellaneous Privileges");
            EntityGroups.Add("Import Customizations", "Customization.Miscellaneous Privileges");
            EntityGroups.Add("Learning Path Authoring", "Customization.Miscellaneous Privileges");
            EntityGroups.Add("Publish Customizations", "Customization.Miscellaneous Privileges");
            EntityGroups.Add("Activate Business Rules", "Customization.Miscellaneous Privileges");
            EntityGroups.Add("Configure Yammer", "Customization.Miscellaneous Privileges");
            EntityGroups.Add("Export Customizations", "Customization.Miscellaneous Privileges");
            EntityGroups.Add("ISV Extensions", "Customization.Miscellaneous Privileges");
            EntityGroups.Add("Modify Customization constraints", "Customization.Miscellaneous Privileges");
            EntityGroups.Add("Retrieve Multiple Social Insights", "Customization.Miscellaneous Privileges");


            MiscPermissionMap.Add("prvPublishRSReport", "Add Reporting Services Reports");
            MiscPermissionMap.Add("prvBulkDelete", "Bulk Delete");
            MiscPermissionMap.Add("prvDeleteAuditPartitions", "Delete Audit Partitions");
            MiscPermissionMap.Add("prvRestoreSqlEncryptionKey", "Manage Data Encryption key - Activate");
            MiscPermissionMap.Add("prvChangeSqlEncryptionKey", "Manage Data Encryption key - Change");
            MiscPermissionMap.Add("prvReadSqlEncryptionKey", "Manage Data Encryption key - Read");
            MiscPermissionMap.Add("prvAdminFilter", "Manage User Synchronization Filters");
            MiscPermissionMap.Add("prvPublishDuplicateRule", "Publish Duplicate Detection Rules");
            MiscPermissionMap.Add("prvCreateOrgEmailTemplates", "Publish Email Templates");
            MiscPermissionMap.Add("prvPublishOrgMailMergeTemplate", "Publish Mail Merge Templates to Organization");
            MiscPermissionMap.Add("prvPublishOrgReport", "Publish Reports");
            MiscPermissionMap.Add("prvDeleteRecordChangeHistory", "Delete Audit Record Change History");
            MiscPermissionMap.Add("prvOneDrive", "OneDrive for Business");
            MiscPermissionMap.Add("prvConfigureSharePoint", "Run SharePoint Integration Wizard");
            MiscPermissionMap.Add("prvReadRecordAuditHistory", "View Audit History");
            MiscPermissionMap.Add("prvReadAuditPartitions", "View Audit Partitions");
            MiscPermissionMap.Add("prvReadAuditSummary", "View Audit Summary");
            MiscPermissionMap.Add("prvConfigureInternetMarketing", "Configure Internet Marketing module");
            MiscPermissionMap.Add("prvAllowQuickCampaign", "Create Quick Campaign");
            MiscPermissionMap.Add("prvUseInternetMarketing", "Use internet marketing module");
            MiscPermissionMap.Add("prvOverridePriceEngineInvoice", "Override Invoice Pricing");
            MiscPermissionMap.Add("prvOverridePriceEngineOpportunity", "Override Opportunity Pricing");
            MiscPermissionMap.Add("prvOverridePriceEngineOrder", "Override Order Pricing");
            MiscPermissionMap.Add("prvQOIOverrideDelete", "Override Quote Order Invoice Delete");
            MiscPermissionMap.Add("prvOverridePriceEngineQuote", "Override Quote Pricing");
            MiscPermissionMap.Add("prvExportToExcel", "Export to Excel");
            MiscPermissionMap.Add("prvGoOffline", "Go Offline in Outlook");
            MiscPermissionMap.Add("prvMailMerge", "Mail Merge");
            MiscPermissionMap.Add("prvPrint", "Print");
            MiscPermissionMap.Add("prvSyncToOutlook", "Sync to Outlook");
            MiscPermissionMap.Add("prvActOnBehalfOfAnotherUser", "Act on Behalf of Another User");
            MiscPermissionMap.Add("prvApproveRejectEmailAddress", "Approve Email Addresses for Users or Queues");
            MiscPermissionMap.Add("prvAssignManager", "Assign manager for a user");
            MiscPermissionMap.Add("prvAssignTerritory", "Assign Territory to User");
            MiscPermissionMap.Add("prvBulkEdit", "Bulk Edit");
            MiscPermissionMap.Add("prvAddressBook", "Dynamics 365 Address Book");
            MiscPermissionMap.Add("prvDisableBusinessUnit", "Enable or Disable Business Unit");
            MiscPermissionMap.Add("prvDisableUser", "Enable or Disable User");
            MiscPermissionMap.Add("prvLanguageSettings", "Language Settings");
            MiscPermissionMap.Add("prvMerge", "Merge");
            MiscPermissionMap.Add("prvOverrideCreatedOnCreatedBy", "Override Created on or Created by for Records during Data Import");
            MiscPermissionMap.Add("prvRollupGoal", "Perform in sync rollups on goals");
            MiscPermissionMap.Add("prvReadLicense", "Read License info");
            MiscPermissionMap.Add("prvReparentBusinessUnit", "Reparent Business unit");
            MiscPermissionMap.Add("prvReparentTeam", "Reparent team");
            MiscPermissionMap.Add("prvReparentUser", "Reparent user");
            MiscPermissionMap.Add("prvSendAsUser", "Send Email as Another User");
            MiscPermissionMap.Add("prvSendInviteForLive", "Send Invitation");
            MiscPermissionMap.Add("prvWriteBusinessClosureCalendar", "Update Business Closures");
            MiscPermissionMap.Add("prvWebMailMerge", "Web Mail Merge");
            MiscPermissionMap.Add("prvBrowseAvailability", "Browse Availability");
            MiscPermissionMap.Add("prvCreateOwnCalendar", "Create own calendar");
            MiscPermissionMap.Add("prvDeleteOwnCalendar", "Delete own calendar");
            MiscPermissionMap.Add("prvReadOwnCalendar", "Read own calendar");
            MiscPermissionMap.Add("prvSearchAvailability", "Search Availability");
            MiscPermissionMap.Add("prvWriteHolidayScheduleCalendar", "Update Holiday Schedules");
            MiscPermissionMap.Add("prvWriteOwnCalendar", "Write own calendar");
            MiscPermissionMap.Add("prvActivateBusinessProcessFlow", "Activate Business Process Flows");
            MiscPermissionMap.Add("prvActivateBusinessRule", "Activate Business Rules");
            MiscPermissionMap.Add("prvActivateSynchronousWorkflow", "Activate Real-time Processes");
            MiscPermissionMap.Add("prvConfigureYammer", "Configure Yammer");
            MiscPermissionMap.Add("prvWorkflowExecution", "Execute Workflow Job");
            MiscPermissionMap.Add("prvExportCustomization", "Export Customizations");
            MiscPermissionMap.Add("prvImportCustomization", "Import Customizations");
            MiscPermissionMap.Add("prvISVExtensions", "ISV Extensions");
            MiscPermissionMap.Add("prvAppendConstraint", "Modify Customization constraints");
            MiscPermissionMap.Add("prvPublishCustomization", "Publish Customizations");
            MiscPermissionMap.Add("prvRetrieveMultipleSocialInsights", "Retrieve Multiple Social Insights");
            MiscPermissionMap.Add("prvPublishArticle", "Publish Articles");
            MiscPermissionMap.Add("prvPromoteToAdmin", "Promote User to Microsoft Dynamics CRM Administrator Role");
            MiscPermissionMap.Add("prvTurnDevErrorsOnOff", "Turn On Tracing");
            MiscPermissionMap.Add("prvAssignPosition", "Assign position for a user");
            MiscPermissionMap.Add("prvWriteHierarchicalSecurityConfiguration", "Change Hierarchy Security Settings");
            MiscPermissionMap.Add("prvControlDecrementTerm", "Control Decrement Terms");
            MiscPermissionMap.Add("prvApproveKnowledgeArticle", "Approve Knowledge Articles");
            MiscPermissionMap.Add("prvPublishKnowledgeArticle", "Publish Knowledge Articles");
            MiscPermissionMap.Add("prvDocumentGeneration", "Document Generation");
            MiscPermissionMap.Add("prvUseTabletApp", "Dynamics 365 for phones express");
            MiscPermissionMap.Add("prvGoMobile", "Dynamics 365 for mobile");
            MiscPermissionMap.Add("prvUseOfficeApps", "Use Dynamics 365 App for Outlook");
            MiscPermissionMap.Add("Customization", "Customizations");
            MiscPermissionMap.Add("Attribute", "Field");
            MiscPermissionMap.Add("Entity", "Entity");
            MiscPermissionMap.Add("EntityKey", "Entity Key");
            MiscPermissionMap.Add("OptionSet", "Option Set");
            MiscPermissionMap.Add("WorkflowSession", "Process Session");
            MiscPermissionMap.Add("Relationship", "Relationship");
            MiscPermissionMap.Add("prvLearningPath", "Learning Path Authoring");
            MiscPermissionMap.Add("Activity", "Activity");
            MiscPermissionMap.Add("NewsArticle", "Announcement");
            MiscPermissionMap.Add("UserQueryVisualizations", "User Chart");
        }
    }
}
